/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: test_zmq.proto */

#ifndef PROTOBUF_C_test_5fzmq_2eproto__INCLUDED
#define PROTOBUF_C_test_5fzmq_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _NatsModel__MsgSyncPlataoStvdT NatsModel__MsgSyncPlataoStvdT;
typedef struct _NatsModel__MsgSyncPlataoStvdRespT NatsModel__MsgSyncPlataoStvdRespT;


/* --- enums --- */


/* --- messages --- */

struct  _NatsModel__MsgSyncPlataoStvdT
{
  ProtobufCMessage base;
  /*
   * tamanho da mensagem 
   */
  uint32_t tamanho;
  /*
   * Número do exercício 
   */
  uint32_t numexe;
  /*
   * Comando enviado pelo PLATAO 
   */
  uint32_t comando;
  /*
   * Horário da máquina 
   */
  uint64_t horamaquina;
  /*
   * Horário do exercício 
   */
  uint32_t horasistema;
  /*
   * Velocidade de execução do exercício 
   */
  uint32_t velocidade;
  /*
   * Contador incremental de 0 a 255 
   */
  uint32_t msgid;
};
#define NATS_MODEL__MSG_SYNC_PLATAO_STVD_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nats_model__msg_sync_platao_stvd_t__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0 }


struct  _NatsModel__MsgSyncPlataoStvdRespT
{
  ProtobufCMessage base;
  uint32_t result;
  size_t n_failedstvds;
  char **failedstvds;
  /*
   * Comando enviado pelo PLATAO 
   */
  uint32_t command;
  /*
   * Contador incremental de 0 a 255 
   */
  uint32_t ref;
  uint32_t reserved;
};
#define NATS_MODEL__MSG_SYNC_PLATAO_STVD_RESP_T__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nats_model__msg_sync_platao_stvd_resp_t__descriptor) \
    , 0, 0,NULL, 0, 0, 0 }


/* NatsModel__MsgSyncPlataoStvdT methods */
void   nats_model__msg_sync_platao_stvd_t__init
                     (NatsModel__MsgSyncPlataoStvdT         *message);
size_t nats_model__msg_sync_platao_stvd_t__get_packed_size
                     (const NatsModel__MsgSyncPlataoStvdT   *message);
size_t nats_model__msg_sync_platao_stvd_t__pack
                     (const NatsModel__MsgSyncPlataoStvdT   *message,
                      uint8_t             *out);
size_t nats_model__msg_sync_platao_stvd_t__pack_to_buffer
                     (const NatsModel__MsgSyncPlataoStvdT   *message,
                      ProtobufCBuffer     *buffer);
NatsModel__MsgSyncPlataoStvdT *
       nats_model__msg_sync_platao_stvd_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nats_model__msg_sync_platao_stvd_t__free_unpacked
                     (NatsModel__MsgSyncPlataoStvdT *message,
                      ProtobufCAllocator *allocator);
/* NatsModel__MsgSyncPlataoStvdRespT methods */
void   nats_model__msg_sync_platao_stvd_resp_t__init
                     (NatsModel__MsgSyncPlataoStvdRespT         *message);
size_t nats_model__msg_sync_platao_stvd_resp_t__get_packed_size
                     (const NatsModel__MsgSyncPlataoStvdRespT   *message);
size_t nats_model__msg_sync_platao_stvd_resp_t__pack
                     (const NatsModel__MsgSyncPlataoStvdRespT   *message,
                      uint8_t             *out);
size_t nats_model__msg_sync_platao_stvd_resp_t__pack_to_buffer
                     (const NatsModel__MsgSyncPlataoStvdRespT   *message,
                      ProtobufCBuffer     *buffer);
NatsModel__MsgSyncPlataoStvdRespT *
       nats_model__msg_sync_platao_stvd_resp_t__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nats_model__msg_sync_platao_stvd_resp_t__free_unpacked
                     (NatsModel__MsgSyncPlataoStvdRespT *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*NatsModel__MsgSyncPlataoStvdT_Closure)
                 (const NatsModel__MsgSyncPlataoStvdT *message,
                  void *closure_data);
typedef void (*NatsModel__MsgSyncPlataoStvdRespT_Closure)
                 (const NatsModel__MsgSyncPlataoStvdRespT *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor nats_model__msg_sync_platao_stvd_t__descriptor;
extern const ProtobufCMessageDescriptor nats_model__msg_sync_platao_stvd_resp_t__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_test_5fzmq_2eproto__INCLUDED */
